@startuml
left to right direction

actor "Utilisateur Financier" as utilisateur

rectangle "Gestion du Budget Personnel" {
    utilisateur -- (Gérer les revenus)
    utilisateur -- (Gérer les dépenses)
    
    utilisateur -- (Générer des rapports mensuels)
    
    utilisateur -- (Gérer les catégories)
    
    utilisateur -- (Définir un budget mensuel)
    utilisateur -- (Suivre la progression du budget)
    
    utilisateur -- (Recevoir des notifications)
    
}
@enduml
